core/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.index, name = 'index'),
  path('login/', views.login_user, name="login"),
  path('login/submit', views.submit_login, name="submit"),
  path('register/', views.register_user, name="register"),
  path('logout/', views.logout_user, name="logout"),
  path('input/', views.insertInput, name='insertInput'),
  path('output/', views.insertOutput, name='insertOutput'),
  path('accounts/', views.accounts, name='accounts'),
  path('accounts/delete/<account>', views.delete_account, name='delete_account'),
  path('accounts/new/', views.create_account, name='new_account'),
  path('accounts/edit/<account>', views.edit_account, name="edit_account"),
  path('extract/', views.extract, name="extract"),
]

finances/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', RedirectView.as_view(url='')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class totalBalance(models.Model):
  '''
  This class contain all infos about
  accounts of users.
  
  Parameters:
             account (text): get account number, this is the primary key
             bank (text): get the name of bank that account is registered
             balance (numeric): get the current value in account at registration time
             register_date (datafield): autofield that get data that account is registered in system  
  '''
  account = models.CharField(max_length=8,
                             verbose_name="Conta",
                             primary_key=True)
  
  bank = models.CharField(max_length=100, 
                          verbose_name="Banco", 
                          )
  
  balance = models.DecimalField(max_digits=20,
                                decimal_places=2, 
                                verbose_name="Saldo",
                                
                                )
  
  register_date = models.DateTimeField(auto_now=True, 
                                       verbose_name="Inserido em")
  
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  
  class Meta:
    db_table = 'totalBalance'
    
  def __str__(self):
    return self.bank


class moneyInputer(models.Model):
  '''
  This model recive all infos about
  inputs values, like salary, tickets,
  etc..
  '''
  
  title = models.CharField(max_length=100,
                           verbose_name="Origem",
                           )
  
  value = models.DecimalField(max_digits=20,
                              decimal_places=2,
                              verbose_name="Valor")
  
  input_date = models.DateField(verbose_name="Data de pagamento")
  
  account = models.ForeignKey('totalBalance', 
                              on_delete=models.CASCADE,
                              verbose_name="Conta"
                              )
  
  
  def __str__(self):
    return self.title

class moneyOutputs(models.Model):
  title = models.CharField(max_length=100,
                           verbose_name="Título",
                           )
  
  CATEGORIES_LIST = (
        ("AL", "ALIMENTAÇÃO"),
        ("CA", "CASA"),
        ("CO", "COMUNICAÇÃO"),
        ("DP", "DESPESAS PESSOAIS"),
        ("IN", "INVESTIMENTOS"),
        ("LZ", "LAZER"),
        ("SA", "SAÚDE"),
        ("TP", "TRANSPORTE")
    )
    
  categories = models.CharField(max_length=100,
                           choices=CATEGORIES_LIST)
    
  
  description = models.TextField(blank=True,
                                 null=True)
  
  value = models.DecimalField(max_digits=20,
                              decimal_places=2,
                              verbose_name="Valor")
  
  output_date = models.DateField(verbose_name="Data de compra")
  
  PAYMENTS_LIST = (
    ('CV', 'Crédito à vista'),
    ('CP', 'Crédito parcelado'),
    ('D', 'Débito')
  )
  
  payment_type = models.CharField(max_length=10,
                                  choices=PAYMENTS_LIST,
                                  ) 
  
  installments = models.DecimalField(max_digits=2,
                                     decimal_places=0,
                                     default=0,
                                     verbose_name="Parcelas")
  
  account = models.ForeignKey('totalBalance',
                              on_delete=models.CASCADE,
                              verbose_name="Conta")
  



  def __str__(self):
    return self.title
  
  def get_output_values(self):
    return self.value * -1

core/views.py
from decimal import Decimal
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Sum, fields
from django.http import HttpResponse, HttpResponseRedirect
from django.http.response import Http404
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from .models import *
from .forms import *


def query_db(user):
    # Get all avaliable balance
    
    current_balance = totalBalance.objects.filter(user=user).aggregate(total=Sum('balance'))['total']
    
    current_balance = f'R${current_balance :.2f}' if current_balance != None else 'R$0.00'

    # Get General Outputs
    outputs = moneyOutputs.objects.all()
    inputs = moneyInputer.objects.all()

    extracts = {
        'outputs': outputs,
        'inputs': inputs,
    }

    extract = []

    for key in extracts.keys():
        for extractvalue in extracts[key]:
            if key == 'outputs':
                extract.append({'value': float(extractvalue.get_output_values()),
                                'date': str(extractvalue.output_date), 
                                'title': str(extractvalue.title)}
                               )
            else:
                extract.append({'value':float(extractvalue.value),
                                'date': str(extractvalue.input_date),
                                'title': str(extractvalue.title)}
                               )

    # Get outpurs in debit
    outputs_debit = moneyOutputs.objects.filter(payment_type__startswith="D").all()

    values_outputs_debit = outputs_debit.aggregate(total=Sum('value'))['total']

    values_outputs_debit = f'R${values_outputs_debit :.2f}' if values_outputs_debit != None else 'R$0.00'

    # Get outputs in credit
    outputs_credit = moneyOutputs.objects.filter(
        payment_type__startswith="C"
    ).all()

    values_outputs_credit = outputs_credit.aggregate(total=Sum('value'))[
        'total']
    values_outputs_credit = f'R${values_outputs_credit :.2f}' if values_outputs_credit != None else 'R$0.00'

    # Get all importants variables
    infos = {
        'current_balance': current_balance,
        'values_outputs_credit': values_outputs_credit,
        'values_outputs_debit': values_outputs_debit,
        'extract': extract,
    }

    return infos

def login_user(request):
    return render(request, 'login.html')

def logout_user(request):
    logout(request)
    return redirect('/')

def submit_login(request):
    
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, 
                            password=password)
                
        if user is not None:
            login(request, user)
            return redirect('/')
        
        else:
            messages.error(request, "Erro: Usuário e/ou Senha Incorreto!")
        
    return redirect('/')

def register_user(request):
    
    form = NewUser(request.POST or None)

    if request.POST:
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Usuário Criado com Sucesso!!!")
            return redirect("/")

        else:
            
            messages.error(request, "O Cadastro do Usuário falhou 😥")
            for field in form:
                for error in field.errors:
                    print(field, error)                   
                    messages.error(request, error)
                       
            return HttpResponseRedirect(reverse('register'))
          
    context = {
        "form": form
    }
    
    
    return render(request, 'register.html', context=context)



@login_required(login_url="/login/")
def index(request):

    user = request.user
    infos = query_db(user)
    name = user.get_full_name()
    

    if request.method == "POST":
        return HttpResponseRedirect(request.POST.get('moviment_type'))
    
    context = {
        'infos': infos,
        'user': user,
        'name': name,
    }    

    return render(request, 'index.html', context=context)

def insertInput(request):

    user = request.user
    infos = query_db(user)

    # form = addInput(request.POST or None, user=user)
    form = addInput(user=user)
    infos['form'] = form

    if request.POST:
        
        form = addInput(user=user, data=request.POST)
        
        if form.is_valid():
            title = request.POST.get('title')
            value = request.POST.get('value')
            input_date = request.POST.get('input_date')
            account_number = request.POST.get('account')

            account = totalBalance.objects.filter(user=user).get(account=account_number)

            account.balance += Decimal(float(value))
            account.save()

            moneyInputer.objects.create(title=title,
                                        value=value,
                                        input_date=input_date,
                                        account=account,
                                        )

    if request.method == "POST":
        return HttpResponseRedirect(request.POST.get('moviment_type'))
    
    context = {
        "user": user,
        "infos": infos,
        "form": form,
    }

    return render(request, 'form_input.html', context=context)


def insertOutput(request):

    user = request.user
    infos = query_db(user)

    form = addOutput(user=user)
    infos['form'] = form

    if request.POST:
        
        form = addOutput(user=user, data=request.POST)
        
        if form.is_valid():
            title = request.POST.get('title')
            categories = request.POST.get('categories')
            description = request.POST.get('description')
            value = request.POST.get('value')
            output_date = request.POST.get('output_date')
            payment_type = request.POST.get('payment_type')
            installments = request.POST.get('installments')

            account_number = request.POST.get('account')
            account = totalBalance.objects.filter(user=user).get(account=account_number)
            

            if payment_type == "D":
                account.balance -= Decimal(float(value))
                account.save()

            moneyOutputs.objects.create(title=title,
                                        categories=categories,
                                        description=description,
                                        value=value,
                                        output_date=output_date,
                                        payment_type=payment_type,
                                        installments=installments,
                                        account=account,
                                        )

    if request.method == "POST":
        return HttpResponseRedirect(request.POST.get('moviment_type'))
    
    context = {
        "user": user,
        "infos": infos,
        "form": form,
    }

    return render(request, 'form_output.html', context=context)


@login_required(login_url="/login/")
def accounts(request):
    '''
    This view function is use to read all accounts
    registered on database
    '''
    user = request.user
    
    registered_accounts = totalBalance.objects.filter(user=user)
    data = request.GET.get('account')    
    
    if data:
        
        messages.warning(request, 'Você tem certeza que deseja deletar essa conta? (Essa ação é irreversível!)')
    
    context = {
        'accounts': registered_accounts,
        'data': data,
    }
    
    

    return render(request, 'accounts.html', context=context)

@login_required(login_url="/login/")
def delete_account(request, account):
    
    if request.POST:
        
        try:
            query = totalBalance.objects.get(account=account)
        except Exception:
            raise Http404()
        
        text_confirm = request.POST.get('text-delete-confirm')
        base = f'{query.bank}/{query.account}'
        
        if text_confirm == base:

            query.delete()

        return HttpResponseRedirect(reverse('accounts'))
    
    pass

@login_required(login_url="/login/")
def create_account(request):
    '''
    This view function is used to add a new account and
    to Edit accounts

    '''
    
    infos = query_db(request.user)

    form = addAccount(request.POST or None)
    infos['form'] = form

    if request.POST:
                
        if form.is_valid():
            data = request.POST
            account = data.get('account')
            bank = data.get('bank')
            balance = data.get('balance')
            user = request.user    
                
            totalBalance.objects.create(
                account=account,
                bank=bank,
                balance=balance,
                user=user
            )
            

            messages.success(request, 'Conta registrada com sucesso!')

            return HttpResponseRedirect(reverse('new_account'))
          
        else:
          
          for field in form:
            for error in field.errors:
              print(field, error)                   
              messages.error(request, error)
          
          return HttpResponseRedirect(reverse('new_account'))

    return render(request, 'create_account.html', context=infos)

@login_required(login_url="/login/")
def edit_account(request, account):
    
    user = request.user
    info = totalBalance.objects.get(account=account)
    
    if user != info.user:
        return redirect('/')
    
    if request.POST:
        
        data = request.POST
        bank = data.get('bank')
        balance = data.get('balance')
                
        info.bank = bank
        info.balance = balance

core/templates/accounts.html
{% extends "base.html" %}


{% block content %}
<div class="content">

    <div class="box">

        {% if not accounts %}
        
            <div class="box-content">
                <p>Nenhuma conta cadastrada!</p>
                <div class="box-subcontent center effect-hover">
                    <a href="{% url 'new_account' %}" >
                        <span>
                            Clique aqui para registrar!
                        </span>
                        
                    </a>
                </div>
            </div>
        {% endif %}

        {% for account in accounts %}
        
        <div class="box-content">
            <h1>{{ account.bank }}</h1>
            <p>Conta: {{ account.account }}</p>
            <p>Saldo: R$ {{ account.balance }}</p>
            <div class="box-subcontent">
                <a href="{% url 'edit_account' account=account.account %}">
                    <span class="edit-account">
                        Editar
                        <i class="fas fa-edit"></i>
                    </span>
                </a>
                <a href="{% url 'accounts' %}?account={{ account.account }}">
                    <span class="delete-account">
                        Excluir
                        <i class="fas fa-trash-alt"></i>
                    </span>
                </a>
            </div>
            
            <!-- Message to confirm delete account option -->
            {% if account.account == data %}
                {% if messages %}
                <div class="message info sm">
                    {% for message in messages %}
                    <p> {{ message }}</p>
                    <form action="delete/{{ account.account }}" method="POST">{% csrf_token %}
                    <span> 
                        Digite <b>{{account.bank}}/{{account.account}}</b> e confirme
                    </span>             
                    <input 
                        type="text" 
                        name="text-delete-confirm" 
                        id="text-delete-confirm" placeholder="{{ account.bank }}/{{ account.account }}"
                        >
                    <button type="submit" class="btn">
                        Confirmar
                    </button>
                    <a href="{% url 'accounts' %}">
                        <button type="button" class="btn">
                            Cancelar
                        </button>
                    </a>
                    </form>
                </div>
                    {% endfor %}
                {% endif %}
            {% endif %}
            <!-- --------------------------------------- -->
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- <meta name="color-scheme" content="dark light"> -->
        {% block title %}
        <title>Finances</title>
        {% endblock %}

    {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="icon" href="{% static 'favicon.ico' %}">
        {% load custom_tags %}
        <script src="https://kit.fontawesome.com/6563b52298.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/toggle-theme.js' %}" defer></script>
    </head>
    <!-- Document BOdy -->
    <body>
        <!-- Navigation Bar -->
        <nav class="navbar">
            <div class='nav-brand'>
                <a href="{% url 'index' %}" class="navbar-brand">
                    <img src="{% static 'logo.png' %}" alt="Gestor de Finanças Pessoais Logo" title="Gestão de Financas Pessoais">
                </a>
            </div>
            <div class="navbar-nav">
                <ul>
                    <li>
                        <a href="{% url 'index' %}">Página Inicial</a>
                    </li>
                    <!-- <li>
            <a href="{% url 'accounts' %}">Contas</a>
          </li> -->
                    <li>
                        <div class="dropdown">
                            <button class="dropbtn">Contas</button>
                            <div class="dropdown-content">
                                <a href="{% url 'new_account' %}">Registrar Conta</a>
                                <a href="{% url 'accounts' %}">Contas Registradas</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <a href="{% url 'extract' %}">Extrato</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Sair</a>
                        <button id="theme-toggle" class="btn" type="button">
                              <i class="fas fa-sun" id="toggle-icon"></i>
                      </button>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- Content of the page -->
        <div class="main">
            {% block content %} {% endblock %}
        </div>
    </body>
    
    <footer>
        Desenvolvindo por
        <b>Alexandre de Freitas Carrascosa</b>
    </footer>

</html>

core/templates/create_account.html
{% extends "base.html" %}

{% block content %}
<div align="center">
<div class="card-box form">
<form method="post">
    {% csrf_token %}
    <h3>Registre uma nova conta</h3>
        <div class="post-form">
            <table>
                {{ form.as_table }}
            </table>
        </div>
        <div class="button-box">
            <button type="submit">Registrar</button>
            <a href="{% url 'accounts' %}">
            <button type="button">Cancelar</button>
            </a>
        </div>
        {% if messages %}
        <div class="messages info">
            {% for message in messages %}
            <p {% if message.tags %} class = "{{ message.tags }}" {% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</form>

</div>
</div> 



{% endblock %}

core/templates/edit_account.html
{% extends 'base.html' %}


{% block content %}
<div align="center">
    <div class="card-box form">
        <form method="post">
            {% csrf_token %}
            <h3>Editando conta {{ account }}</h3>
            <div class="post-form">
                <table>
                    <tr>
                        <th>
                            <label for="id_account">Conta:</label>
                        </th>
                        <td>
                            {{ account }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <label for="id_bank">Banco:</label>
                        </th>
                        <td>
                            <input
                                type="text"
                                name="bank"
                                maxlength="100"
                                required
                                id="id_bank"
                                value = "{{ bank }}"
                            >
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <label for="id_balance">Saldo:</label>
                        </th>
                        <td>
                            <input
                                type="number"
                                name="balance"
                                step="0.01"
                                required
                                id="id_balance"
                                value = "{{ balance }}"
                            >
                        </td>
                    </tr>
                </table>
            </div>
            <div class="button-box">
                <button type="submit">Editar</button>
                <a href="{% url 'accounts' %}">
                    <button type="button">Cancelar</button>
                </a>
            </div>
            {% if messages %}
            <div class="messages info">
                {% for message in messages %}
                <p {% if message.tags %} class = "{{ message.tags }}" {% endif %}>{{ message }}</p>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </form>
</div>
</div>
{% endblock %}

core/templates/extract.html
{% extends 'base.html' %} 

{% block content %}

<div class="content">
    <div class="extract-box">
        <h1>Movimentações</h1>
        <table class="table table-bordered">
            <tbody>
                {% for extract in extracts %}
                    <tr>
                        <td>{{ extract.date }}</td>
                        <td>{{ extract.title }}</td>
                        <td>R$ {{ extract.value }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        {% if extracts.has_other_pages %}
        <ul class="pagination">
            {% if extracts.has_previous %}
                <li><a href="?page={{ extract.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in extracts.paginator.page_range %}
                    {% if extracts.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
            {% endfor %}
            {% if extracts.has_next %}
                <li><a href="?page={{ extracts.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
    </div>
    <div class="graph-box">
        <h1>Gráficos</h1>
        <div class="graph">
        {% if graph %}
            {{ graph }}
        {% endif %}
        </div>
    </div>
</div>

{% endblock %}

core/templates/form.html
<form method="POST">
    {% csrf_token %}
    <h3>Inserir Movimentações</h3>
    <div align="center">
        <label>Selecione o tipo de movimentação:</label>
        <select name="moviment_type" onchange="this.form.submit()">
            <option value ="{% url 'index' %}"> ------- </option>
            <option value="{% url 'insertInput' %}">Entrada</option>
            <option value="{% url 'insertOutput' %}">Saída</option>
        </select>

    </div>

core/templates/form_input.html
{% extends 'index.html' %}

{% block form %}
<div class="post-form">
    <table>
    {{ form.as_table }}
    </table>
</div>
<div class="button-box">
    <button type="submit">Registrar</button>
</div>
</div>
</form>
{% endblock %}

core/templates/form_output.html
{% extends 'index.html' %}


{% block form %}
<div class="post-form">
    <table>
        {{ form.as_table }}
    </table>

</div>
<div class="button-box">
    <a href="submit/">
        <button type="submit">Registrar</button>
    </a>
</div>
</form>
</div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}

{% load custom_tags %}

{% block content %}

<h1> Olá, {{ user.first_name }}!</h1>
<h2>Veja as Informações Gerais sobre suas finanças</h2>

<div class="content">
    <div class="card-box sm">
        <h3>Saldo</h3>
        <p>{{ infos.current_balance }}</p>
        <div class="mini-box">
            <a href="{% url 'accounts' %}">
                <span>
                    Ir para contas
                    <i class="fas fa-arrow-right"></i>
                </span>
            </a>
        </div>
    </div>
    <div class="card-box lg">
        <h3>Compras & Gastos</h3>
        <p>Débito: {{ infos.values_outputs_debit }}</p>
        <p>Crédito: {{ infos.values_outputs_credit }}</p>
        <div class="mini-box">
            <a href="{% url 'extract' %}">
                <span>
                    Ir para extrato
                    <i class="fas fa-arrow-right"></i>
                </span>
            </a>
        </div>
    </div>

    <div class="card-box lg extra">
        {% include 'form.html' %}
        {% block form %}
        {% endblock %}
    </div>
    </div>
    
{% endblock %}
 

core/templates/login.html
{% extends 'base.html' %}

{% block content %}

<div align="center">
    <div class="card-box form">
        <form action='{% url "submit" %}' method="POST"> {% csrf_token %}
            <h2>Login</h2>
            <div class="post-form">
                <table>
                    <tr>
                        <th>
                            <label>Usuário:</label>
                        </th>
                        <td>
                            <input 
                                type="text"
                                name="username"
                                required> 
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <label>Senha:</label>
                        </th>
                        <td>
                            <input 
                                type="password" 
                                name="password" 
                                required>
                        </td>
                    </tr>
                </table>
            
            </div>
            <div class="button-box login">
                <button type="submit">Entrar</button>
                
            </div>
            <p class="login">Não tem um conta?
                <a href="{% url 'register' %}">Registre-se</a>
            </p>         

        </form>
    </div>
    </div>
    <div class="message-info alert">
        {% for message in messages %}
            <h5>
                {{ message }}
            </h5>
        {% endfor %}
</div>


{% endblock %}

core/templates/register.html
{% extends 'login.html' %}

{% block content %}

<div align="center">
    <div class="card-box form lg">
        <form method="POST">
            {% csrf_token %}
            <h2>Registre-se</h2>
            <div class="post-form text-left">
                <table>
                    {{ form }}
                </table>
            </div>
            <div class="button-box login">
                <button type="submit">Registrar-se</button>
                
            </div>
            <p class="login">Já tem um conta? Faça o
                <a href="{% url 'login' %}">Login</a>
            </p> 
        </form>
    </div>
</div>
<div class="message-info alert">
    {% for message in messages %}
        <div>
            {{ message }}
        </div>
    {% endfor %}
</div>


{% endblock %}